

import pytz


def Interpolate(inp1, res1, inp2, res2, inp3):
  """Given inp1 -> res1 and inp2 -> res2 relationship, return res3 for inp3"""
  inpdelta = inp2 - inp1
  resdelta = res2 - res1
  if inpdelta != 0.0:  # Input points are different, so result can be calculated.
    res3 = ((inp3 - inp1) * float(resdelta / inpdelta)) + res1
  else:  # 2 input points are the same, result is unknown.
    res3 = res1  # Default to first result.
  return res3

def CompassPoint(
  value,
  points=[
    "N",
    "NNE",
    "NE",
    "ENE",
    "E",
    "ESE",
    "SE",
    "SSE",
    "S",
    "SSW",
    "SW",
    "WSW",
    "W",
    "WNW",
    "NW",
    "NNW",
  ],
):
  """Convert a degree value into a compass point.
  Default is 16 point compass.
  8 and 4 point compass can be generated by changing the points parameter.
  points=['N','E','S','W']
  or
  points=['N','NE','E','SE','S','SW','W','NW']             ."""
  locn = int(round((value / 360) * len(points), 0)) % len(points)
  return points[locn]

def AngleToHMS(value):
  """Convert a decimal angle into Hours, Minutes, Seconds."""
  value = 24 * value / 360  # Convert from DEGREES to HOURS.
  h = value // 1  # Integer division. How many whole hours.
  value = float(value) - h  # Fractions of an hour left.
  value = value * 60  # Convert to minutes.
  m = value // 1  # Integer division. How many whole minutes.
  s = float(value) - m  # Fractions of a minute left.
  s = s * 60  # Convert to seconds.
  h = int(h)  # return integer rather than float values.
  m = int(m)
  return h, m, s

def AngleToDMS(value):
  """Convert a decimal angle into Degrees, Minutes, Seconds."""
  if value < 0:
    sign = -1
  else:
    sign = 1
  value = abs(value)  # Strip out sign.
  d = value // 1  # Integer division. How many whole degrees?
  value = float(value) - d  # Fractions of an hour left.
  value = value * 60  # Convert to minutes.
  m = value // 1  # Integer division. How many whole minutes.
  s = float(value) - m  # Fractions of a minute left.
  s = s * 60  # Convert to seconds.
  d = int(d * sign)  # return integer rather than float values.
  m = int(m * sign)
  s = s * sign
  return d, m, s

def HMSToAngle(h, m=None, s=None, invert=True):
  """Convert hours, minutes, seconds to angle.
  Input values can be decimals, they will be converted correctly.
  invert = True: minutes and seconds values are made negative if hour value is negative.
  """
  if invert and h < 0:
    if m > 0:
      m = -1 * m
    if s > 0:
      s = -1 * s
  angle = h * 360 / 24  # Convert HOURS to angle.
  if m is not None:  # Minutes were specified, add those.
    angle += (m / 60) * 360 / 24
  if s is not None:  # Seconds were specified, add those.
    angle += (s / (60 * 60)) * 360 / 24
  return angle

def SubtractList(list1, list2):
  """Subtract list 2 from list 1"""
  result = [a for a in list1 if a not in list2]
  return result

def UniqueList(list1):
  """Return only unique entries from a list.
  Does not preserve order."""
  result = list(
    set(list1)
  )  # Convert via 'set()' which reduces to unique hashable entries.
  return result

def DMSToAngle(degrees=0.0, minutes=0.0, seconds=0.0):
  """Convert degrees, minutes and seconds into degrees."""
  # Convert all values relative to 360 degrees.
  minutes = (1 / 60) * float(minutes)
  seconds = (1 / (60 * 60)) * float(seconds)
  value = degrees + minutes + seconds
  return value

def DisplayHMS(h, m, s, length=12, rounding=1):
  """Display HMS values in human readable format.
  h = hours.
  m = minutes.
  s = seconds (can be decimal).
  length = length of returned string.
  rounding = number of decimals precision in the seconds value."""
  hs = str(int(h))
  if len(hs) < 2:
    hs = hs.rjust(2)
  ms = str(int(m))
  if len(ms) < 2:
    ms = ms.rjust(2)
  ss = str(round(s, rounding))
  if len(ss.split(".")[0]) < 2:
    ss = " " + ss
  DH = hs + "h " + ms + "m " + ss + "s"
  DH = DH.rjust(length, " ")[(-1 * length) :]
  return DH

def DisplayDegree(value, length=10, zerofill=True, symbol=None):
  """Display a degree decimal with 3dp and right justified to specified length.
  length = size of field to return (value right justified)
       = None: Don't fill or justify.
  zerofill = True: zerofill leading and trailing digits.
  zerofill = False: zerofill only trailing digits.
  symbol = symbol or text to use as 'degree' unit."""
  if value is None:  # No value, just return blank.
    disp = str(value).rjust(length, " ")
  else:  # Value, format it.
    if zerofill:  # Leading zeros should be filled.
      disp = str(format(abs(value), "07.3f"))  # Fill without sign.
      if value < 0:
        disp = "-" + disp  # Add sign back.
    else:  # Leading zeros not required.
      disp = str(format(value, ".3f"))
    if symbol is not None:
      disp += symbol
    if length is not None:  # Field length specified, right justify to fit.
      disp = ((" " * length) + disp)[(-1 * length) :]
  return disp

def Deg3dp(value, symbol=None):
  """Turn a degree decimal into a simple zerofilled, 3dp string.

  45.0     -->> 045.000
  -45      -->> -045.000

  45,'deg' -->> 045.000deg

  """
  if value is not None:
    result = DisplayDegree(value, length=None, symbol=symbol)
    if value >= 0:
      result = " " + result  # blank space where '+' sign would be.
  else:
    result = "None"  # No value set.
  return result
