"""Astronomical calculations and celestial coordinate systems."""

from .celestrak import Celestrak
from .trig import (
    alt_az_to_xyz,
    angle_to_dms,
    angle_to_hms,
    az_alt_text,
    calculate_vector,
    compass_point,
    compound_angle,
    compound_relative_angle,
    deg_3dp,
    display_degree,
    dms_to_angle,
    hms_to_angle,
    pixel_to_center_vector,
    ra_dec_text,
    relative_alt_az,
    rotate_xyz_on_x_axis,
    rotate_xyz_on_z_axis,
    vector_to_pixel,
    xyz_to_alt_az,
)

__all__ = [
    "compass_point",
    "angle_to_hms",
    "angle_to_dms",
    "hms_to_angle",
    "dms_to_angle",
    "display_degree",
    "deg_3dp",
    "alt_az_to_xyz",
    "rotate_xyz_on_z_axis",
    "rotate_xyz_on_x_axis",
    "xyz_to_alt_az",
    "relative_alt_az",
    "calculate_vector",
    "compound_angle",
    "compound_relative_angle",
    "vector_to_pixel",
    "pixel_to_center_vector",
    "az_alt_text",
    "ra_dec_text",
    "Celestrak",
]
