#!/usr/bin/python3
"""Trigonometry functions for celestial calculations."""

from typing import Tuple  # For type hinting.
import math


def compass_point(
    value,
    points=None,
):
    """Convert a degree value into a compass point.
    Default is 16 point compass.
    8 and 4 point compass can be generated by changing the points parameter.
    points=['N','E','S','W']
    or
    points=['N','NE','E','SE','S','SW','W','NW']             ."""
    if points is None:
        points = [
            "N",
            "NNE",
            "NE",
            "ENE",
            "E",
            "ESE",
            "SE",
            "SSE",
            "S",
            "SSW",
            "SW",
            "WSW",
            "W",
            "WNW",
            "NW",
            "NNW",
        ]
    locn = int(round((value / 360) * len(points), 0)) % len(points)
    return points[locn]


# ------------------------------------------------------------------


def angle_to_hms(value):
    """Convert a decimal angle into Hours, Minutes, Seconds."""
    value = 24 * value / 360  # Convert from DEGREES to HOURS.
    h = value // 1  # Integer division. How many whole hours.
    value = float(value) - h  # Fractions of an hour left.
    value = value * 60  # Convert to minutes.
    m = value // 1  # Integer division. How many whole minutes.
    s = float(value) - m  # Fractions of a minute left.
    s = s * 60  # Convert to seconds.
    h = int(h)  # return integer rather than float values.
    m = int(m)
    return h, m, s


# ------------------------------------------------------------------


def angle_to_dms(value):
    """Convert a decimal angle into Degrees, Minutes, Seconds."""
    if value < 0:
        sign = -1
    else:
        sign = 1
    value = abs(value)  # Strip out sign.
    d = value // 1  # Integer division. How many whole degrees?
    value = float(value) - d  # Fractions of an hour left.
    value = value * 60  # Convert to minutes.
    m = value // 1  # Integer division. How many whole minutes.
    s = float(value) - m  # Fractions of a minute left.
    s = s * 60  # Convert to seconds.
    d = int(d * sign)  # return integer rather than float values.
    m = int(m * sign)
    s = s * sign
    return d, m, s


# ------------------------------------------------------------------


def hms_to_angle(h, m=None, s=None, invert=True):
    """Convert hours, minutes, seconds to angle.
    Input values can be decimals, they will be converted correctly.
    invert = True: minutes and seconds values are made negative if hour value is negative.
    """
    if invert and h < 0:
        if m is not None and m > 0:
            m = -1 * m
        if s is not None and s > 0:
            s = -1 * s
    angle = h * 360 / 24  # Convert HOURS to angle.
    if m is not None:  # Minutes were specified, add those.
        angle += (m / 60) * 360 / 24
    if s is not None:  # Seconds were specified, add those.
        angle += (s / (60 * 60)) * 360 / 24
    return angle


# ------------------------------------------------------------------


def dms_to_angle(degrees=0.0, minutes=0.0, seconds=0.0):
    """Convert degrees, minutes and seconds into degrees."""
    # Convert all values relative to 360 degrees.
    minutes = (1 / 60) * float(minutes)
    seconds = (1 / (60 * 60)) * float(seconds)
    value = degrees + minutes + seconds
    return value


# ------------------------------------------------------------------


def display_hms(h, m, s, length=12, rounding=1):
    """Display HMS values in human readable format.
    h = hours.
    m = minutes.
    s = seconds (can be decimal).
    length = length of returned string.
    rounding = number of decimals precision in the seconds value."""
    hs = str(int(h))
    if len(hs) < 2:
        hs = hs.rjust(2)
    ms = str(int(m))
    if len(ms) < 2:
        ms = ms.rjust(2)
    ss = str(round(s, rounding))
    if len(ss.split(".", maxsplit=1)[0]) < 2:
        ss = " " + ss
    dh = hs + "h " + ms + "m " + ss + "s"
    dh = dh.rjust(length, " ")[(-1 * length) :]
    return dh


# ------------------------------------------------------------------


def display_degree(value, length=10, zerofill=True, symbol=None):
    """Display a degree decimal with 3dp and right justified to specified length.
    length = size of field to return (value right justified)
           = None: Don't fill or justify.
    zerofill = True: zerofill leading and trailing digits.
    zerofill = False: zerofill only trailing digits.
    symbol = symbol or text to use as 'degree' unit."""
    if value is None:  # No value, just return blank.
        disp = str(value).rjust(length, " ")
    else:  # Value, format it.
        if zerofill:  # Leading zeros should be filled.
            disp = str(format(abs(value), "07.3f"))  # Fill without sign.
            if value < 0:
                disp = "-" + disp  # Add sign back.
        else:  # Leading zeros not required.
            disp = str(format(value, ".3f"))
        if symbol is not None:
            disp += symbol
        if length is not None:  # Field length specified, right justify to fit.
            disp = ((" " * length) + disp)[(-1 * length) :]
    return disp


# ------------------------------------------------------------------


def deg_3dp(value, symbol=None):
    """Turn a degree decimal into a simple zerofilled, 3dp string.

    45.0     -->> 045.000
    -45      -->> -045.000

    45,'deg' -->> 045.000deg

    """
    if value is not None:
        result = display_degree(value, symbol=symbol)
        if value >= 0:
            result = " " + result  # blank space where '+' sign would be.
    else:
        result = "None"  # No value set.
    return result


# ------------------------------------------------------------------


def alt_az_to_xyz(
    alt: float, az: float, distance: float = 1.0
) -> Tuple[float, float, float]:
    """Convert alt,az angles to XYZ coordinates. Based upon originlab definition on web.
    X and Y web definitions are swapped to match alignment in Pilomar space.
    Z = ZENITH - NADIR axis. ZENITH is +ve. NADIR is -ve.
    X = EAST - WEST axis.    EAST is +ve.   WEST is -ve.
    Y = NORTH - SOUTH axis.  NORTH is +ve.  SOUTH is -ve.
    """
    try:
        y = distance * math.cos(math.radians(alt)) * math.cos(math.radians(az))
        x = distance * math.cos(math.radians(alt)) * math.sin(math.radians(az))
        z = distance * math.sin(math.radians(alt))
    except Exception as e:  # pylint: disable=broad-except
        print("pilomartrig: AltAzToXYZ(", alt, az, distance, ") Failed:", e)
        x = y = z = 0.0
    return x, y, z


# ------------------------------------------------------------------


def rotate_xyz_on_z_axis(x, y, z, angle):
    """Rotate x,y cooordinates by an angle around z axis.
    Z = ZENITH - NADIR axis. ZENITH is +ve. NADIR is -ve.
    X = EAST - WEST axis.    EAST is +ve.   WEST is -ve.
    Y = NORTH - SOUTH axis.  NORTH is +ve.  SOUTH is -ve.
    """
    try:
        hyp = math.sqrt(x * x + y * y)
        orig_angle = math.degrees(math.atan2(y, x))
        new_angle = orig_angle - angle
        new_x = math.cos(math.radians(new_angle)) * hyp
        new_y = math.sin(math.radians(new_angle)) * hyp
    except Exception as e:  # pylint: disable=broad-except
        print("pilomartrig: RotateXYZonZaxis(", x, y, z, angle, ") Failed:", e)
        new_x = new_y = None
    return new_x, new_y, z


# ------------------------------------------------------------------


def rotate_xyz_on_x_axis(x, y, z, angle) -> Tuple[float, float, float]:
    """Rotate y,z cooordinates by an angle around x axis.
    Z = ZENITH - NADIR axis. ZENITH is +ve. NADIR is -ve.
    X = EAST - WEST axis.    EAST is +ve.   WEST is -ve.
    Y = NORTH - SOUTH axis.  NORTH is +ve.  SOUTH is -ve.
    """
    try:
        hyp = math.sqrt(y * y + z * z)
        orig_angle = math.degrees(math.atan2(z, y))
        new_angle = orig_angle + angle
        new_y = math.cos(math.radians(new_angle)) * hyp
        new_z = math.sin(math.radians(new_angle)) * hyp
    except Exception as e:  # pylint: disable=broad-except
        print("pilomartrig: RotateXYZonXaxis(", x, y, z, angle, ") Failed:", e)
        x = new_y = new_z = 0.0
    return x, new_y, new_z


# ------------------------------------------------------------------


def xyz_to_alt_az(x: float, y: float, z: float) -> Tuple[float, float]:
    """Convert 3D coordinates into altitude and azimuth.
    Z = ZENITH - NADIR axis. ZENITH is +ve. NADIR is -ve.
    X = EAST - WEST axis.    EAST is +ve.   WEST is -ve.
    Y = NORTH - SOUTH axis.  NORTH is +ve.  SOUTH is -ve.
    """
    try:
        hyp = math.sqrt(x * x + y * y)
        alt = math.degrees(math.atan2(z, hyp))
        az = math.degrees(math.atan2(x, y)) % 360
    except Exception as e:  # pylint: disable=broad-except
        print("pilomartrig: XYZToAltAz(", x, y, z, ") Failed:", e)
        alt = 0.0
        az = 0.0
    return alt, az


# ------------------------------------------------------------------


def relative_alt_az(star_alt, star_az, look_at_alt, look_at_az):
    """Calculate the angles of a star relative to some look-at position.
    There will be some wonderfully clever maths to do this cleanly, quickly and precisely.
    But this was developed with trial and error,
    and it works well enough for me and is modifiable as required.
    """
    plot_x, plot_y, plot_z = alt_az_to_xyz(
        star_alt, star_az
    )  # Place star on celestial sphere (unit 1)

    # Swing round to LOOK-AT Azimuth.
    new_y = plot_y * math.cos(math.radians(-1 * look_at_az)) - plot_x * math.sin(
        math.radians(-1 * look_at_az)
    )  # 0degrees is due north on Y axis. 90degrees is due east on X axis.
    new_x = plot_x * math.cos(math.radians(-1 * look_at_az)) + plot_y * math.sin(
        math.radians(-1 * look_at_az)
    )
    plot_x = new_x
    plot_y = new_y

    # Drop down to LOOK-AT Altitude.
    new_y = plot_y * math.cos(math.radians(-1 * look_at_alt)) - plot_z * math.sin(
        math.radians(-1 * look_at_alt)
    )  # 0degrees is due north on Y axis. 90degrees is straight up on Z axis.
    new_z = plot_z * math.cos(math.radians(-1 * look_at_alt)) + plot_y * math.sin(
        math.radians(-1 * look_at_alt)
    )
    plot_y = new_y
    plot_z = new_z

    plot_star_alt, plot_star_az = xyz_to_alt_az(
        plot_x, plot_y, plot_z
    )  # Convert from an x,y,z location back into Alt/Az combination.
    # Clip result to +/- 180Degrees because we're relative to the 'centre' of the map we're drawing.
    plot_star_az = plot_star_az % 360
    if plot_star_az > 180:
        plot_star_az -= 360
    plot_star_alt = plot_star_alt % 360
    if plot_star_alt > 180:
        plot_star_alt -= 360
    return plot_star_alt, plot_star_az


# ------------------------------------------------------------------


def calculate_vector(from_x, from_y, to_x, to_y):
    """Return ANGLE and PIXEL DISTANCE from 1 point to another."""
    x_dist = to_x - from_x
    y_dist = to_y - from_y
    pix_dist = round(math.sqrt((x_dist**2) + (y_dist**2)), 0)
    pix_angle = round(math.degrees(math.atan2(x_dist, y_dist)), 0)
    return pix_dist, pix_angle


# ------------------------------------------------------------------


def compound_angle(alt, az):
    """Given alt,az, return compound angle from 0,0 to the point."""
    r_comp = math.degrees(
        math.acos(math.cos(math.radians(az)) * math.cos(math.radians(alt)))
    )  # Compound angle from Alt & Az combined.
    return r_comp


# ------------------------------------------------------------------


def compound_relative_angle(to_alt, to_az, from_alt, from_az):
    """Calculate angular displacement of (to_alt, to_az) from (from_alt, from_az)
    Used to calculate if something is within field of view."""
    r_x, r_y, r_z = alt_az_to_xyz(to_alt, to_az)  # Convert TO position to 3d space.
    r_x, r_y, r_z = rotate_xyz_on_z_axis(
        r_x, r_y, r_z, -1 * from_az
    )  # Subtract FROM position.
    r_x, r_y, r_z = rotate_xyz_on_x_axis(r_x, r_y, r_z, -1 * from_alt)
    r_alt, r_az = xyz_to_alt_az(
        r_x, r_y, r_z
    )  # Convert RELATIVE position back to alt/az.
    if r_alt > 180:
        r_alt = r_alt - 360  # Keep within +/1 180 degrees
    if r_az > 180:
        r_az = r_az - 360
    r_alt = abs(r_alt)  # All values +ve distances.
    r_az = abs(r_az)
    r_comp = compound_angle(
        alt=r_alt, az=r_az
    )  # Compound angle from Alt & Az combined.
    return r_comp


# ------------------------------------------------------------------


def vector_to_pixel(from_x, from_y, pix_dist, pix_angle):
    """Given ANGLE and PIXEL DISTANCE from 1 point, return the resulting point."""
    rad = math.radians(pix_angle)
    to_x = pix_dist * math.sin(rad) + from_x
    to_y = pix_dist * math.cos(rad) + from_y
    return int(to_x), int(to_y)


# ------------------------------------------------------------------


def pixel_to_center_vector(to_x, to_y, width, height):
    """Given any pixel location in an image, return its
    vector relative to the centre of the image.
    """
    pix_dist, pix_angle = calculate_vector(int(width / 2), int(height / 2), to_x, to_y)
    return pix_dist, pix_angle


# ------------------------------------------------------------------


def az_alt_text(az, alt, symbol=None) -> str:
    """Return standardised string of Altitude and Azimuth coordinates."""
    if symbol is None:
        symbol = "deg"
    return f"az: {deg_3dp(az)}{symbol} alt: {deg_3dp(alt)}{symbol}"


# ------------------------------------------------------------------


def ra_dec_text(radeg, decdeg, symbol=None):
    """Return standardised string of RA and Dec coordinates."""
    th, tm, ts = angle_to_hms(radeg)  # Convert deg to hms.
    temp = display_hms(th, tm, ts).strip()  # Convert to string.
    return f"RA: {temp} Dec: {deg_3dp(decdeg)}{symbol}"  # Return entire string.


# ------------------------------------------------------------------
