"""Core utilities and base classes for the Pilomar telescope control system."""

from .base import AttributeMaster
from .converters import (
    dts_to_datetime,
    is_float,
    is_int,
    string_to_datetime,
    text_to_float,
    text_to_int,
    utc_string_to_datetime,
)
from .logger import LogFile
from .time_utils import (
    clean_datetime_string,
    datetime_2_ts,
    display_dt,
    display_hms_from_stamp,
    display_now_hms,
    hms_from_stamp,
    hr_bytes,
    hr_hertz,
    hr_seconds,
    interpolate,
    local_to_utc,
    now_hms,
    now_utc,
    set_clock_offset,
    set_display_timezone,
    set_local_timezone,
    set_timescale,
    skyfield_now,
    ts_2_datetime,
    ts_delta,
    utc_time_stamp,
    utc_to_display,
    utc_to_local,
)
from .timer import ProgressTimer, Timer

__all__ = [
    "AttributeMaster",
    "Timer",
    "ProgressTimer",
    "LogFile",
    "utc_string_to_datetime",
    "dts_to_datetime",
    "string_to_datetime",
    "is_float",
    "is_int",
    "text_to_int",
    "text_to_float",
    # Time utilities
    "now_utc",
    "skyfield_now",
    "ts_2_datetime",
    "datetime_2_ts",
    "ts_delta",
    "utc_to_local",
    "utc_to_display",
    "local_to_utc",
    "clean_datetime_string",
    "hms_from_stamp",
    "display_hms_from_stamp",
    "now_hms",
    "display_now_hms",
    "hr_seconds",
    "hr_bytes",
    "hr_hertz",
    "set_timescale",
    "set_clock_offset",
    "set_local_timezone",
    "set_display_timezone",
    "interpolate",
    "utc_time_stamp",
    "display_dt",
]
